version: 2.1

orbs:
  php: circleci/php@1.1.0
workflows:
  build_and_test:
    jobs:
      - build_and_test
jobs:
  build_and_test:
    docker:
      - image: circleci/php:7.4.9-cli-buster
    steps:
      - checkout
      - run: |
          sudo apt update -y &&
          sudo apt install -y libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libgmp-dev re2c libmhash-dev libmcrypt-dev file zlib1g-dev  &&
          sudo ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/

      - php/install-composer:
          install-version: 2.1.0
      - php/install-packages

      - run:
          name: View PHP environment
          command: |
            php -v &&
            composer --version &&
            ./vendor/bin/phpunit --version
      - run:
          name: Phpunit tests
          command: |
            ./vendor/bin/phpunit --log-junit test-results/phpunit/junit.xml
      - store_test_results:
          path: test-results